stages:
  make_dataset:
    cmd: python src/data/make_dataset.py
    deps:
    - src/data/make_dataset.py
    params:
     - make_dataset.test_size
    outs:
    - data/raw
  build_feature:
    cmd: python src/features/build_features.py
    deps:
    - data/raw
    - src/features/build_features.py
    outs:
    - data/processed
  feature_enginring:
    cmd: python src/features/feature_enginring.py
    deps:
    - data/processed
    - src/features/feature_enginring.py
    params:
     - feature_enginring.max_features
    outs:
    - data/interim
  train_data:
    cmd: python src/model/train_model.py
    deps:
    - data/interim
    - src/model/train_model.py
    params:
     - train_model.n_estimators
     - train_model.learning_rate
    outs:
    - models/model.pkl

  predit_model:
    cmd: python src/model/predict_model.py
    deps:
    - models/model.pkl
    - src/model/predict_model.py
    outs:
    - reports/metrics.json
